#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

env_dir="${OPENSHIFT_SCS_DIR}/env"

function set_shoutcast_option ()
{
	var=${1^^}
	name="OPENSHIFT_SCS_CONF_$var"
	set_env_var $name $2 $env_dir 
}

function set_info ()
{
	var=${1^^}
	name="OPENSHIFT_SCS_$var"
	set_env_var $name $2 $env_dir 
}

function shoutcast_conf_exists ()
{
	varopt2=${1^^}
	confname="CONFIG_${varopt2}"
	
	if ! -f "${OPENSHIFT_DATA_DIR}/sc_${confname}.conf" ; then
		return 0
	else
		return 1
	fi
}

function add_env_conf ()
{
	var=${1}
	varopt=${1^^}
	
	name="OPENSHIFT_SCS_CONF_${varopt}"
	
	varopt2=${2^^}
	confname="CONFIG_$varopt2"
	
	if ! -f "${OPENSHIFT_DATA_DIR}/sc_${confname}.conf" ; then
		create_shoutcast_conf $varopt2
	fi
	
	echo "$var=${$name}" >> "${OPENSHIFT_DATA_DIR}/sc_${confname}.conf"
}

function add_shoutcast_conf ()
{
	varopt2=${2^^}
	confname="CONFIG_$varopt2"
	
	if ! -f "${OPENSHIFT_DATA_DIR}/sc_${confname}.conf" ; then
		create_shoutcast_conf $varopt2
	fi
	
	echo "${1}" >> "${OPENSHIFT_DATA_DIR}/sc_${confname}.conf"
}

function create_shoutcast_conf ()
{
	varopt=${1^^}
	name="CONFIG_$varopt"
	echo "\n" > "${OPENSHIFT_DATA_DIR}/sc_$name.conf"
}